### ISSUE TITLE
feature:欄位驗證邏輯

### ISSUE THREAD

**Issue by southAndy** [The-peek-of-purple-forbidde/Credit-Card-Form#2]
### README

1. commit 規則
新增功能：`feat: finished <features>`
修改功能(解衝突,`merge` etc..)：`fix:modify <features>`

2. 開發方式
請在`develop`上創建自己的分支進行作業

3. 溝通模式
開發上的溝通請使用 issue 及 PR 的 comment
（請勿打私訊騷擾，尤其是Rex）

### Desc

關於你負責的內容：
輸入內容各類驗證，（不足處可參考：https://github.com/jquense/yup）

---

### Tasks
- [ ] 型別驗證
- [ ] 長度驗證
- [ ] 空白鍵驗證
- [ ] 亂碼驗證

**Comment by cc5324** [comment]
@southAndy  請問 PM 大大，驗證的模組應該放在哪個資料夾比較適合？(直接放在components/裡面嗎)?

**Comment by southAndy** [comment]
@cc5324 
拆分出來好了,都會模組了
(ps)常常使用`git pull`,健康安心

**Comment by cc5324** [comment]
拆分出來是指在 src/ 新增一個 validation 的資料夾嗎？

**Comment by southAndy** [comment]
@cc5324 
我自己會放在`src/assets/validation/validation.js`,這樣,提供參考
